export const clerkAppearance = {
  cssLayerName: "clerk" as const,
  baseTheme: undefined,
  variables: {
    colorPrimary: "#C0001A",
    colorForeground: "hsl(var(--foreground))",
    colorMutedForeground: "hsl(var(--muted-foreground))",
    colorDanger: "#C0001A",
    colorBackground: "hsl(var(--background))",
    colorInput: "hsl(var(--input))",
    colorInputForeground: "hsl(var(--foreground))",
    colorNeutral: "hsl(var(--border))",
    fontFamily: "DM Sans, sans-serif",
    borderRadius: "0.5rem",
  },
  elements: {
    rootBox: "w-full flex justify-center",
    cardBox: "rounded-2xl w-[440px] max-w-full overflow-hidden",
    card: "!shadow-none !border-0 !bg-transparent !rounded-none",
    footer: "!shadow-none !border-0 !bg-transparent !rounded-none",
    headerTitle: "font-serif text-foreground",
    headerSubtitle: "text-muted-foreground",
    socialButtonsBlockButtonText: "text-foreground",
    formFieldLabel: "text-foreground",
    footerActionLink: "text-[#C0001A]",
    footerActionText: "text-muted-foreground",
    dividerText: "text-muted-foreground",
    identityPreviewEditButton: "text-[#C0001A]",
    formFieldSuccessText: "text-green-600",
    alertText: "text-foreground",
    logoBox: "",
    logoImage: "",
    socialButtonsBlockButton: "",
    formButtonPrimary: "bg-[#C0001A] hover:bg-[#a0001a]",
    formFieldInput: "",
    footerAction: "",
    dividerLine: "",
    alert: "",
    otpCodeFieldInput: "",
    formFieldRow: "",
    main: "",
  },
};
